### ISSUE TITLE
Connection timeout

### ISSUE THREAD

**Issue by alicerum** [miguno/wirbelsturm#17]
Hello! I've just cloned the repository, set up everything, bootstrapped it and, when deploying the first vb host, i get connection timeout, after which deploying stops. What could i do to get it working?

Ubuntu 13.10, java 7. Virtual box 4.3.14, vagrant 1.6.3

**Comment by shawnhe** [comment]
It appears that the image is built with AMD architecture, and wouldn't work on an Intel machine.
