### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by hodiapa** [miguno/wirbelsturm#32]
Hi, 

I am having issues with regards to not finding the puppet modules folder. I checked on my directory listing and it actually does not exists. Attaching installation log.
```
=====================================
Output of GIT Bash running on windows 8
====================================
Welcome to Git (version 1.9.4-preview20140929)

Run 'git help git' to display the help index.
Run 'git help <command>' to display help for specific commands.

user@JJHG7X1 /C/Users/wirbelsturm (ma
ster)
$ ./bootstrap
+---------------------------+
| BOOTSTRAPPING WIRBELSTURM |
+---------------------------+
Preparing Ruby environment...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4942  100  4942    0     0  13213      0 --:--:-- --:--:-- --:--:-- 13213
Detecting desired Ruby version: OK (1.9.3-p362)
Checking for rvm: NOT FOUND (If you already ran ruby-bootstrap: have you perform
ed the post-installation steps?)
Installing latest stable version of rvm...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   184  100   184    0     0    274      0 --:--:-- --:--:-- --:--:--   274
100 22817  100 22817    0     0  28664      0 --:--:-- --:--:-- --:--:-- 28664
BASH 3.2.25 required (you have 3.1.20(4)-release)
Checking Vagrant environment...
Checking for Vagrant: OK
Preparing Vagrant environment...
Installing the 'vagrant-hosts --version '>= 2.1.4'' plugin. This can take a few
minutes...
Installed the plugin 'vagrant-hosts (2.3.0)'!
Installing the 'vagrant-aws' plugin. This can take a few minutes...
Installed the plugin 'vagrant-aws (0.6.0)'!
Installing the 'vagrant-awsinfo' plugin. This can take a few minutes...
Installed the plugin 'vagrant-awsinfo (0.0.8)'!
==> box: Adding box 'centos6-compatible' (v0) for provider: virtualbox
    box: Downloading: http://puppet-vagrant-boxes.puppetlabs.com/centos-65-x64-v
irtualbox-puppet.box
    box: Progress: 100% (Rate: 700k/s, Estimated time remaining: --:--:--)
==> box: Successfully added box 'centos6-compatible' (v0) for 'virtualbox'!
==> box: Adding box 'centos6-compatible' (v0) for provider: aws
    box: Downloading: https://github.com/mitchellh/vagrant-aws/raw/master/dummy.
box
    box: Progress: 100% (Rate: 244/s, Estimated time remaining: --:--:--)
==> box: Successfully added box 'centos6-compatible' (v0) for 'aws'!
Checking Puppet environment...
Checking for librarian-puppet: NOT FOUND
Please run 'bundle install' and then re-run bootstrap

user@JJHG7X1 /C/Users/wirbelsturm (ma
ster)
$ vagrant status
Current machine states:

zookeeper1                not created (virtualbox)
nimbus1                   not created (virtualbox)
supervisor1               not created (virtualbox)
supervisor2               not created (virtualbox)

This environment represents multiple VMs. The VMs are all listed
above with their current state. For more information about a specific
VM, run `vagrant status NAME`.

user@JJHG7X1 /C/Users/wirbelsturm (ma
ster)
$ vagrant up
Bringing machine 'zookeeper1' up with 'virtualbox' provider...
Bringing machine 'nimbus1' up with 'virtualbox' provider...
Bringing machine 'supervisor1' up with 'virtualbox' provider...
Bringing machine 'supervisor2' up with 'virtualbox' provider...
There are errors in the configuration of this machine. Please fix
the following errors and try again:

puppet provisioner:
* The configured module path doesn't exist: c:/Users/wirbelsturm/puppet/modules
```

**Comment by miguno** [comment]
I am afraid that we have never tried to run Wirbelsturm on a Windows host -- only on Linux and Macs.  Unfortunately I can't really help you with your problem. :-(

**Comment by miguno** [comment]
Addendum: We also have no plans to support Windows unfortunately.

**Comment by aquaindian** [comment]
Hello Miguno, I am facing the same problem on Ubuntu as well...first the 'librarian-puppet' was not installed so I did that manually but later this one came up.
Unfortunately I dont know puppet etc. so well and was hoping if you can shine some light on this.
Thanks ...
 
Here's the log of 'bootstrap' and 'vagrant up':
**********************************************************
ashish@ubuntu:~/wirbelsturm$ ./bootstrap
+---------------------------+
| BOOTSTRAPPING WIRBELSTURM |
+---------------------------+
Preparing Ruby environment...
./bootstrap: line 49: curl: command not found
Checking Vagrant environment...
Checking for Vagrant: OK
Preparing Vagrant environment...
Installing the 'vagrant-hosts --version '>= 2.1.4'' plugin. This can take a few minutes...
Installed the plugin 'vagrant-hosts (2.3.0)'!
Installing the 'vagrant-aws' plugin. This can take a few minutes...
Installed the plugin 'vagrant-aws (0.6.0)'!
Installing the 'vagrant-awsinfo' plugin. This can take a few minutes...
Installed the plugin 'vagrant-awsinfo (0.0.8)'!
==> box: Adding box 'centos6-compatible' (v0) for provider: virtualbox
    box: Downloading: http://puppet-vagrant-boxes.puppetlabs.com/centos-65-x64-virtualbox-puppet.box
==> box: Successfully added box 'centos6-compatible' (v0) for 'virtualbox'!
==> box: Adding box 'centos6-compatible' (v0) for provider: aws
    box: Downloading: https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box
==> box: Successfully added box 'centos6-compatible' (v0) for 'aws'!
Checking Puppet environment...
Checking for librarian-puppet: OK
Preparing Puppet environment...
Could not resolve the dependencies.
Checking for known problems...
ashish@ubuntu:~/wirbelsturm$ vagrant up
Bringing machine 'zookeeper1' up with 'virtualbox' provider...
Bringing machine 'nimbus1' up with 'virtualbox' provider...
Bringing machine 'supervisor1' up with 'virtualbox' provider...
Bringing machine 'supervisor2' up with 'virtualbox' provider...
There are errors in the configuration of this machine. Please fix
the following errors and try again:

puppet provisioner:
* The configured module path doesn't exist: /home/ashish/wirbelsturm/puppet/modules
**********************************************************

**Comment by miguno** [comment]
One of the first lines in your log output says "curl: command not found".  Please install curl and try again, and check for similar such hints in the logs if you run into errors again.
