### ISSUE TITLE
zookeeper1: Downloading: centos6-compatible

### ISSUE THREAD

**Issue by jtfogarty** [miguno/wirbelsturm#39]
I'm getting the below error on OS X with the latest of virtualbox and 1.7.2 of vagrant;

```
jeffs-mbp:wirbelsturm Jeff$ vagrant up
Bringing machine 'zookeeper1' up with 'virtualbox' provider...
Bringing machine 'nimbus1' up with 'virtualbox' provider...
Bringing machine 'supervisor1' up with 'virtualbox' provider...
Bringing machine 'supervisor2' up with 'virtualbox' provider...
Bringing machine 'kafka1' up with 'virtualbox' provider...
==> zookeeper1: Box 'centos6-compatible' could not be found. Attempting to find and install...
    zookeeper1: Box Provider: virtualbox
    zookeeper1: Box Version: >= 0
==> zookeeper1: Adding box 'centos6-compatible' (v0) for provider: virtualbox
    zookeeper1: Downloading: centos6-compatible
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

Couldn't open file /Users/Jeff/wirbelsturm/centos6-compatible
```

**Comment by miguno** [comment]
This might be a (temporary?) problem with your Internet connection.

**Comment by miguno** [comment]
Also, have you run `./bootstrap`?

**Comment by jtfogarty** [comment]
the ./bootstrap helped but now I get;
jeffs-mbp:wirbelsturm Jeff$ vagrant up
Bringing machine 'zookeeper1' up with 'virtualbox' provider...
Bringing machine 'nimbus1' up with 'virtualbox' provider...
Bringing machine 'supervisor1' up with 'virtualbox' provider...
Bringing machine 'supervisor2' up with 'virtualbox' provider...
Bringing machine 'kafka1' up with 'virtualbox' provider...
There are errors in the configuration of this machine. Please fix
the following errors and try again:

vm:
* The '' provisioner could not be found.

**Comment by miguno** [comment]
Do you have Virtualbox installed?  In any case I'd recommend to re-read the Wirbelsturm installation instructions.
