### ISSUE TITLE
How to access ZK and Kafka instances with local install for development?

### ISSUE THREAD

**Issue by wpoosanguansit** [miguno/wirbelsturm#41]
Hi,

I did install successfully and I am able to run the instances as instructed in the readme.  However when I try to access the ZK and Kafka instance from my code I am not able to.  From the ip checked, it comes back as 10.0.2.15 for both.  Is there anything I need to set to allow access from my code?  Thanks for your help.

**Comment by miguno** [comment]
From where are you running your code?  The safest way is to run the code within one of the VMs.

Also, what does your `wirbelsturm.yaml` look like?

**Comment by wpoosanguansit** [comment]
I am running my code locally on my dev box.  And I have the VMBox running locally as well.  So I am trying to access Kafka and Storm from my code which I run in my local box.  This should be like accessing over the network.  Which I am still not sure what do I need to set to allow the access.  All instances are running and I can vagrant ssh into them.

Here is the yaml

# When using Amazon AWS the domain should be your hosted Route 53 sub-domain.
domain: your-wirbelsturm-sub.domain.com
environment: default-environment
aws:
  local_user: ec2-user
  rclocal_url: https://s3.amazonaws.com/yum.miguno.com/bootstrap/aws/rc.local
  keypair_name: CHANGEME       # Example: wirbelsturm
  private_key_path: CHANGEME   # Example: ~/.ssh/wirbelsturm.pem
  # This keypair is used by Vagrant to boot and provision an instance.  It must be allowed to start/stop EC2 instances.
  deploy_user:
    aws_access_key: CHANGEME   # Example: ABCDEFGHIJ1234567890
    aws_secret_key: CHANGEME   # Example: abcdefghijklmnopqrstuvwxyz12345678901234
  # This keypair is used by Wirbelsturm (not Vagrant) during bootstrapping to update DNS from within the running
  # instance.  It must be allowed to manage Route 53.
  in_instance_user:
    aws_access_key: CHANGEME   # Example: ZYXZYXZYXZ1234567890
    aws_secret_key: CHANGEME   # Example: zyxzyxzyxzyxzyxzyxzyxzyxzyx1234567890123

nodes:
  # Deploys ZooKeeper servers.
  zookeeper_server:
    count: 1
    # Do not change the hostname prefix because it is used in the Hiera YAML configuration data.
    hostname_prefix: zookeeper
    ip_range_start: 10.0.0.240
    node_role: zookeeper_server
    providers:
      virtualbox:
        memory: 512
      aws:
        instance_type: m1.xlarge
        ami: ami-abc12345
        security_groups:
          - wirbelsturm
  # Deploys Storm master machines running Storm's Nimbus and UI daemons.
  storm_master:
    # Unless you know what you are doing there should be only one Storm master (Nimbus).
    count: 1
    # Do not change the hostname prefix because it is used in the Hiera YAML configuration data.
    hostname_prefix: nimbus
    ip_range_start: 10.0.0.250
    node_role: storm_master
    providers:
      virtualbox:
        memory: 768
        forwarded_ports:
          - guest: 8080 # Storm UI
            host: 28080
      aws:
        instance_type: m1.xlarge
        ami: ami-abc12345
        security_groups:
          - wirbelsturm
  # Deploys Storm slave machines running Storm's Supervisor daemons.
  storm_slave:
    count: 2
    hostname_prefix: supervisor
    ip_range_start: 10.0.0.100
    node_role: storm_slave
    providers:
      virtualbox:
        memory: 1024
      aws:
        instance_type: c1.xlarge
        ami: ami-abc12345
        security_groups:
          - wirbelsturm
#  # Deploys Kafka brokers.
  kafka_broker:
    count: 1
    hostname_prefix: kafka
    ip_range_start: 10.0.0.20
    node_role: kafka_broker
    providers:
      virtualbox:
        memory: 1536
      aws:
        instance_type: m2.2xlarge
        ami: ami-abc12345
        security_groups:
          - wirbelsturm
#  # Deploys Redis server instances.
#  redis_server:
#    count: 1
#    hostname_prefix: redis
#    ip_range_start: 10.0.0.30
#    node_role: redis_server
#    providers:
#      virtualbox:
#        memory: 512
#      aws:
#        instance_type: m2.2xlarge
#        ami: ami-abc12345
#        security_groups:
#          - wirbelsturm
#  # Deploys single-node Storm clusters, with Nimbus/Supervisor/UI (and ZooKeeper) all running on the same machine.
#  storm_single_node_cluster:
#    count: 1 # If you want a multi-node cluster, use storm_master and storm_slave above.
#    hostname_prefix: stormsingle
#    ip_range_start: 10.0.0.40
#    node_role: storm_single
#    providers:
#      virtualbox:
#        memory: 2048
#        forwarded_ports:
#          - guest: 8080 # Storm UI
#            host: 28081
#      aws:
#        instance_type: m1.xlarge
#        ami: ami-abc12345
#        security_groups:
#          - wirbelsturm
#  # Deploys Wirbelsturm build servers.
#  build_server:
#    count: 1
#    hostname_prefix: build
#    ip_range_start: 10.0.0.50
#    node_role: wirbelsturm_build_server
#    providers:
#      virtualbox:
#        memory: 1024
#      aws:
#        instance_type: t1.micro
#        ami: ami-abc12345
#        security_groups:
#          - wirbelsturm
#  # Deploys monitoring servers running Graphite (through nginx) and Diamond.
#  monitoring_server:
#    count: 1
#    hostname_prefix: monitor
#    ip_range_start: 10.0.0.60
#    node_role: monitoring
#    providers:
#      virtualbox:
#        memory: 2048
#        forwarded_ports:
#          - guest: 8080 # Graphite Web UI -- login with user "admin" and password "wirbelsturm"
#            host: 38080
#      aws:
#        instance_type: m2.2xlarge
#        ami: ami-abc12345
#        security_groups:
#          - wirbelsturm


Thanks for your help.

**Comment by miguno** [comment]
In this case you need to add port forwarding, see the example of `storm_master` in your `wirbelsturm.yaml`.

Keep in mind though that enabling port forwarding may not be enough;  you may also need to configure e.g. Kafka to respond to requests with an IP address other than `10.x.x.x` -- otherwise the code running on your host machine would still get confused.  For Kafka, see `host.name` and `advertised.host.name` as described in the [Kafka docs](http://kafka.apache.org/documentation.html).

That being said, the easiest path to success for you would be to run your code within the VMs, where you don't need port forwarding or other such shenanigans.

**Comment by wpoosanguansit** [comment]
Let me try that.  Thanks for your help.

**Comment by miguno** [comment]
Looks like this worked for you.  I am closing the ticket.
