### ISSUE TITLE
Problems with deploying on AWS: parameter groupId is invalid

### ISSUE THREAD

**Issue by netalpha** [miguno/wirbelsturm#42]
``` sh
 # VAGRANT_LOG=info vagrant up nimbus1 --provider=aws
```

==> nimbus1:   - [ sh, -c, 'echo "export AWS_ACCESS_KEY_ID=\$AWS_ACCESS_KEY" >> /etc/aws/aws-credentials.sh' ]
==> nimbus1:   - [ sh, -c, 'echo "export AWS_SECRET_ACCESS_KEY=\$AWS_SECRET_KEY" >> /etc/aws/aws-credentials.sh' ]
==> nimbus1:   - [ chmod, 400, /etc/aws/aws-credentials.sh ]
==> nimbus1:   - [ wget, "https://s3.amazonaws.com/yum.miguno.com/bootstrap/aws/rc.local", -O, "/etc/rc.d/rc.local" ]
==> nimbus1:   - [ chown, "root:root", /etc/rc.d/rc.local ]
==> nimbus1:   - [ chmod, 755, /etc/rc.d/rc.local ]
==> nimbus1:   - [ /etc/rc.d/rc.local ]
==> nimbus1:
==> nimbus1: --===============8357495029070803742==--
 INFO interface: info:  -- Block Device Mapping: []
 INFO interface: info: ==> nimbus1:  -- Block Device Mapping: []
==> nimbus1:  -- Block Device Mapping: []
 INFO interface: info:  -- Terminate On Shutdown: false
 INFO interface: info: ==> nimbus1:  -- Terminate On Shutdown: false
==> nimbus1:  -- Terminate On Shutdown: false
 INFO interface: info:  -- Monitoring: false
 INFO interface: info: ==> nimbus1:  -- Monitoring: false
==> nimbus1:  -- Monitoring: false
 INFO interface: info:  -- EBS optimized: false
 INFO interface: info: ==> nimbus1:  -- EBS optimized: false
==> nimbus1:  -- EBS optimized: false
 INFO interface: info:  -- Assigning a public IP address in a VPC: false
 INFO interface: info: ==> nimbus1:  -- Assigning a public IP address in a VPC: false
==> nimbus1:  -- Assigning a public IP address in a VPC: false
 INFO interface: warn: Warning! Vagrant might not be able to SSH into the instance.
Please check your security groups settings.
 INFO interface: warn: ==> nimbus1: Warning! Vagrant might not be able to SSH into the instance.
==> nimbus1: Please check your security groups settings.
==> nimbus1: Warning! Vagrant might not be able to SSH into the instance.
==> nimbus1: Please check your security groups settings.
ERROR warden: Error occurred: There was an error talking to AWS. The error message is shown
below:

InvalidParameterValue => Value () for parameter groupId is invalid. The value cannot be empty
 INFO warden: Beginning recovery process...
 INFO warden: Calling recover: #<VagrantPlugins::AWS::Action::RunInstance:0x000001023e9100>
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
ERROR warden: Error occurred: There was an error talking to AWS. The error message is shown
below:

InvalidParameterValue => Value () for parameter groupId is invalid. The value cannot be empty
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
ERROR warden: Error occurred: There was an error talking to AWS. The error message is shown
below:

InvalidParameterValue => Value () for parameter groupId is invalid. The value cannot be empty
 INFO warden: Beginning recovery process...
 INFO warden: Calling recover: #<Vagrant::Action::Builtin::Call:0x00000100bb7bb8>
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO environment: Released process lock: machine-action-31267fa52a22e23fe6caeea06ca2b355
 INFO environment: Running hook: environment_unload
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 1 hooks defined.
 INFO runner: Running action: environment_unload #<Vagrant::Action::Builder:0x00000101157d20>
ERROR vagrant: Vagrant experienced an error! Details:
ERROR vagrant: #<VagrantPlugins::AWS::Errors::FogError: There was an error talking to AWS. The error message is shown
below:

InvalidParameterValue => Value () for parameter groupId is invalid. The value cannot be empty>
ERROR vagrant: There was an error talking to AWS. The error message is shown
below:

InvalidParameterValue => Value () for parameter groupId is invalid. The value cannot be empty
ERROR vagrant: /Users/netalpha/.vagrant.d/gems/gems/vagrant-aws-0.6.0/lib/vagrant-aws/action/run_instance.rb:113:in `rescue in call'
/Users/netalpha/.vagrant.d/gems/gems/vagrant-aws-0.6.0/lib/vagrant-aws/action/run_instance.rb:101:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
/Users/netalpha/.vagrant.d/gems/gems/vagrant-aws-0.6.0/lib/vagrant-aws/action/elb_register_instance.rb:16:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
/Users/netalpha/.vagrant.d/gems/gems/vagrant-aws-0.6.0/lib/vagrant-aws/action/warn_networks.rb:14:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/synced_folders.rb:86:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/provision.rb:80:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builder.rb:116:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `block in run'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/util/busy.rb:19:in `busy'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `run'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/call.rb:53:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
/Users/netalpha/.vagrant.d/gems/gems/vagrant-aws-0.6.0/lib/vagrant-aws/action/connect_aws.rb:43:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/handle_box.rb:56:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builder.rb:116:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `block in run'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/util/busy.rb:19:in `busy'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `run'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:214:in `action_raw'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:191:in `block in action'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:516:in `lock'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:178:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:178:in `action'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
 INFO interface: error: There was an error talking to AWS. The error message is shown
below:

InvalidParameterValue => Value () for parameter groupId is invalid. The value cannot be empty
There was an error talking to AWS. The error message is shown
below:

InvalidParameterValue => Value () for parameter groupId is invalid. The value cannot be empty
 INFO interface: Machine: error-exit ["VagrantPlugins::AWS::Errors::FogError", "There was an error talking to AWS. The error message is shown\nbelow:\n\nInvalidParameterValue => Value () for parameter groupId is invalid. The value cannot be empty"]

**Comment by salzamt** [comment]
what was the problem here? I am getting the same error message.
as long as I am not using any security group at all it works. when I use one, I get this error.

**Comment by yuriferreira** [comment]
I am getting the same error message here.

**Comment by guy-mograbi-at-gigaspaces** [comment]
me too

**Comment by josdirksen** [comment]
The problem in my case was that I had to specify the security group by name, not by Id.

**Comment by miguno** [comment]
To double check -- isn't this already documented in [AWS.md](https://github.com/miguno/wirbelsturm/blob/master/docs/AWS.md#full-wirbelsturmyaml-configuration-example-for-aws)?

Quoting:
> Note: Security groups are specified by name in non-VPC environments (e.g. my-custom-name). When using Amazon VPC however you must specify the security groups by their id (e.g. sg-123abc456).

**Comment by josdirksen** [comment]
Yes apparently it is. But the error message isn't really that helpful.

**Comment by miguno** [comment]
@ josdirksen: Yeah, Vagrant and/or AWS could be a bit more descriptive.  For that reason I added the note to the docs (we ran into the same problem at the beginning).

**Comment by mamoit** [comment]
I just stumbled upon this error message, and indeed, the error message is far from helpful.

**Comment by andrepapaz** [comment]
I can solve problem with right region, right ami for this region and generate a new Key Pair on my right region on Amazon, also i remove my vagrant apt-get and install from website, and update my plugins.

**Comment by chrisspen** [comment]
The AWS message is next to useless. It means you either didn't specify a security group name or specified one that was invalid. This happened to me, and I was specifying a name for a group that didn't exist.
