### ISSUE TITLE
IP collission error, server failure when changing IPs

### ISSUE THREAD

**Issue by arduima** [miguno/wirbelsturm#44]
IP error when using default .yml file but when changing the IPs to something like `10.10.10.XXX` I get failures for all the servers when using the deploy script.
Are there any other options I have to change when modifying the IPs?

Error below. 
```
The specified host network collides with a non-hostonly network!
This will cause your specified IP to be inaccessible. Please change
the IP or name of your host only network so that it no longer matches that of
a bridged or non-hostonly network.
```

**Comment by miguno** [comment]
* Can you provide more details, e.g. the full contents of your `wirbelsturm.yaml` file as well as the full output of the deploy step?
* Also, perhaps your (host) machine is already using the `10.10.10.XXX` for something else.  I'd double-check that.  You can also try to use a different IP range, e.g. `10.10.20.XXX` and see if that makes a difference.

**Comment by miguno** [comment]
Closed because of inactivity.  Feel free to re-open if needed.
